RunnersPal.Core/Controllers/RunLogController.cs
using System.Net.Mime;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RunnersPal.Core.Controllers.ApiModels;
using RunnersPal.Core.Models;
using RunnersPal.Core.Repository;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
[Produces(MediaTypeNames.Application.Json)]
public class RunLogController(ILogger<RunLogController> logger,
    IUserAccountRepository userAccountRepository,
    IRunLogRepository runLogRepository,
    IUserService userService,
    IPaceService paceService)
    : ControllerBase
{
    [HttpGet("activities")]
    public async IAsyncEnumerable<RunLogEventApiModel> Activities([FromQuery] DateTime date)
    {
        var userAccount = await userAccountRepository.GetUserAccountAsync(User);
        logger.LogDebug("Getting run log activities for user account id = {UserAccountId}", userAccount.Id);
        await foreach (var runLog in runLogRepository.GetByDateAsync(userAccount, date))
            yield return new(runLog.Id, DateOnly.FromDateTime(runLog.Date), $"{userService.ToUserDistance(runLog.Route.Distance, userAccount)} in {paceService.TimeTakenDisplayFormat(runLog.TimeTaken)}", paceService.CalculatePace(userAccount, runLog));
    }
}

RunnersPal.Core/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RunnersPal.Core.Pages;

public class IndexModel : PageModel
{
    public void OnGet() { }
}

RunnersPal.Core/Pages/RoutePal/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Pages.RoutePal;

public class IndexModel(IUserService userService)
    : PageModel
{
    public bool IsLoggedIn => userService.IsLoggedIn;

    public void OnGet() { }
}

RunnersPal.Core/Pages/RoutePal/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Models;
using RunnersPal.Core.Repository;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Pages.RoutePal;

[Authorize]
public class ListModel(IUserAccountRepository userAccountRepository,
    IUserService userService,
    IUserRouteService userRouteService)
    : PageModel
{
    private Dictionary<int, Models.RunLog> _lastRunsForRoutes = [];
    private UserAccount? _userAccount;
    [BindProperty(SupportsGet = true)] public int PageNumber { get; set; } = 1;
    [BindProperty(SupportsGet = true)] public string? Find { get; set; }
    [BindProperty(SupportsGet = true)] public string? Sort { get; set; }
    public IEnumerable<Models.Route> Routes { get; private set; } = [];
    public Pagination Pagination { get; private set; } = Pagination.Empty;

    public async Task OnGet()
    {
        _userAccount = await userAccountRepository.GetUserAccountAsync(User);
        Find = string.IsNullOrEmpty(Find) ? null : Find.Trim();
        var (userRoutes, lastRunsForRoutes) = await userRouteService.GetUserRoutesAsync(_userAccount, Find, Sort);
        _lastRunsForRoutes = lastRunsForRoutes;
        var routes = Pagination.Paginate(userRoutes, PageNumber);
        Routes = routes.Items;
        Pagination = new(routes.Page, routes.PageCount);
    }

    public async Task<string> RouteDistanceAsync(Models.Route route)
        => userService.ToUserDistance(route.Distance, _userAccount ??= await userAccountRepository.GetUserAccountAsync(User));

    public Models.RunLog? LastRun(Models.Route route)
        => _lastRunsForRoutes.TryGetValue(route.Id, out var runLog) ? runLog : null;
}

RunnersPal.Core/Pages/RoutePal/Map.cshtml.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Repository;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Pages.RoutePal;

public class MapModel(ILogger<MapModel> logger,
    IUserService userService,
    IUserAccountRepository userAccountRepository,
    IRouteRepository routeRepository)
    : PageModel
{
    [BindProperty(SupportsGet = true)] public string? ShareLink { get; set; }
    [BindProperty(SupportsGet = true)] public int? RouteId { get; set; }
    [BindProperty(SupportsGet = true)] public bool? LoadUnsaved { get; set; }
    [BindProperty(SupportsGet = true)] public string? Unit { get; set; }
    [BindProperty] public string? RouteName { get; set; }
    [BindProperty] public string? RouteNotes { get; set; }
    [BindProperty] public string? Points { get; set; }
    [BindProperty] public decimal Distance { get; set; }
    [BindProperty] public string? Delete { get; set; }
    public bool IsRouteDeleted { get; private set; }
    public bool IsLoggedIn => userService.IsLoggedIn;
    public string ShareLinkUrl { get; private set; } = "";

    public async Task<IActionResult> OnGet()
    {
        if (!string.IsNullOrEmpty(ShareLink))
        {
            if (RouteId != null)
            {
                logger.LogInformation("RouteId should not be used when ShareLink is provided");
                return BadRequest();
            }

            var route = await routeRepository.FindRouteByShareLinkAsync(ShareLink);
            if (route == null)
            {
                logger.LogInformation("Route {ShareLink} cannot be found", ShareLink);
                return Redirect($"/routepal/mapnotfound?sharelink={ShareLink}");
            }

            if (string.IsNullOrEmpty(route.MapPoints))
            {
                logger.LogInformation("Route {RouteId} is not a mapped route and should not be shared, cannot view this route", route.Id);
                return BadRequest();
            }

            if (userService.IsLoggedIn && route.RouteType == Models.Route.PrivateRoute && route.Creator == (await userAccountRepository.GetUserAccountAsync(User)).Id)
            {
                logger.LogInformation("Route {RouteId} is owned by the current user, redirecting to normal route view", route.Id);
                return Redirect($"/routepal/map?routeid={route.Id}");
            }

            RouteName = route.Name;
            Points = route.MapPoints ?? "";
            Distance = route.Distance;
            RouteNotes = route.Notes ?? "";
            IsRouteDeleted = route.RouteType == Models.Route.DeletedRoute;
        }

        if (RouteId != null)
        {
            if (!userService.IsLoggedIn)
            {
                logger.LogInformation("No User authenticated, cannot load any route, redirecting to login page");
                return LocalRedirect($"/signin?ReturnUrl={WebUtility.UrlEncode($"/routepal/map?routeid={RouteId}")}");
            }

            var userAccount = await userAccountRepository.GetUserAccountAsync(User);
            var route = await routeRepository.GetRouteAsync(RouteId.Value);
            if (route == null || route.Creator != userAccount.Id)
            {
                logger.LogWarning("Route {RouteId} is not owned by user {UserAccountId}, cannot view this route", RouteId, userAccount.Id);
                return BadRequest();
            }

            if (string.IsNullOrEmpty(route.MapPoints))
            {
                logger.LogWarning("Route {RouteId} is not a mapped route, cannot view this route", RouteId);
                return BadRequest();
            }

            RouteName = route.Name;
            Points = route.MapPoints ?? "";
            Distance = route.Distance;
            RouteNotes = route.Notes ?? "";
            IsRouteDeleted = route.RouteType == Models.Route.DeletedRoute;
            ShareLinkUrl = string.IsNullOrEmpty(route.ShareLink) ? "" : Url.PageLink(pageName: "/routepal/map", values: new { route.ShareLink }, protocol: Request.Scheme) ?? "";
        }

        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        if (!userService.IsLoggedIn)
        {
            logger.LogWarning("No User authenticated, redirecting to login page");
            return LocalRedirect($"/signin?ReturnUrl={WebUtility.UrlEncode("/routepal/map?loadunsaved=true")}");
        }

        if (string.IsNullOrWhiteSpace(RouteName) || string.IsNullOrWhiteSpace(Points))
        {
            logger.LogInformation("Route is missing a name or points, cannot save");
            return BadRequest();
        }

        var userAccount = await userAccountRepository.GetUserAccountAsync(User);

        if (RouteId != null)
        {
            var route = await routeRepository.GetRouteAsync(RouteId.Value);
            if (route?.Creator != userAccount.Id)
            {
                logger.LogWarning("Route {RouteId} not found or is not owned by user {UserAccountId}, cannot update this route", RouteId, userAccount.Id);
                return BadRequest();
            }

            if (route.RouteType != Models.Route.PrivateRoute)
            {
                logger.LogWarning("Route {RouteId} is not an active, private route, cannot save", RouteId);
                return BadRequest();
            }

            if (!string.IsNullOrEmpty(Delete))
            {
                await routeRepository.DeleteRouteAsync(route);
                return Redirect("/routepal");
            }

            var updatedRoute = await routeRepository.UpdateRouteAsync(route, userAccount, RouteName, Points, Distance, RouteNotes);
            RouteId = updatedRoute.Id;
        }
        else if (string.IsNullOrEmpty(Delete))
        {
            var newRoute = await routeRepository.CreateNewRouteAsync(userAccount, RouteName, Points, Distance, RouteNotes, null);
            RouteId = newRoute.Id;
        }
        else
        {
            logger.LogInformation("No route id, but delete has been set - cannot delete an unknown route");
            return BadRequest();
        }

        return Redirect($"/routepal/map?routeid={RouteId}");
    }

    public async Task<string> UserUnitsAsync()
        => !userService.IsLoggedIn && !string.IsNullOrEmpty(Unit)
            ? string.Equals(Unit, "miles", StringComparison.InvariantCultureIgnoreCase) ? "miles" : "km"
            : (Models.DistanceUnits?)(await userAccountRepository.GetUserAccountOrNullAsync(User))?.DistanceUnits switch { Models.DistanceUnits.Miles => "miles", Models.DistanceUnits.Kilometers => "km", _ => "km" };

    public async Task<decimal> UserUnitsMultiplierAsync()
        => !userService.IsLoggedIn && !string.IsNullOrEmpty(Unit)
            ? string.Equals(Unit, "miles", StringComparison.InvariantCultureIgnoreCase) ? 1000 * UserService.KilometersToMiles : 1000
            : (Models.DistanceUnits?)(await userAccountRepository.GetUserAccountOrNullAsync(User))?.DistanceUnits switch { Models.DistanceUnits.Miles => 1000 * UserService.KilometersToMiles, Models.DistanceUnits.Kilometers => 1000, _ => 1000 };

    public string SwitchToUnit => string.Equals(Unit, "miles", StringComparison.InvariantCultureIgnoreCase) ? "km" : "miles";
}

RunnersPal.Core/Pages/RunLog.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RunnersPal.Core.Pages;

public class RunLogModel : PageModel
{
    public Task OnGet() => Task.CompletedTask;
}

RunnersPal.Core/Pages/RunLog/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Pages.RunLog;

public class IndexModel(IUserService userService) : PageModel
{
    [BindProperty(SupportsGet = true)] public DateTime Date { get; set; } = DateTime.Today;
    public string InitialDate => Date.ToString("yyy-MM-dd");

    public void OnGet() { }

    public bool IsLoggedIn => userService.IsLoggedIn;
}

RunnersPal.Core/Pages/RunLog/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Models;
using RunnersPal.Core.Repository;
using RunnersPal.Core.Services;

namespace RunnersPal.Core.Pages.RunLog;

[Authorize]
public class ListModel(
    ILogger<ListModel> logger,
    IUserAccountRepository userAccountRepository,
    IUserService userService,
    IPaceService paceService,
    IRunLogRepository runLogRepository,
    IRouteRepository routeRepository)
    : PageModel
{
    private UserAccount? _userAccount;

    [BindProperty(SupportsGet = true)] public int PageNumber { get; set; } = 1;
    [BindProperty(SupportsGet = true)] public int? RouteId { get; set; }
    public string Date { get; set; } = "";
    public string RouteName { get; set; } = "";
    public IEnumerable<Models.RunLog> Activities { get; set; } = [];
    public Pagination Pagination { get; private set; } = Pagination.Empty;

    public async Task OnGet()
    {
        var userAccount = await GetUserAccountAsync();
        if (RouteId != null)
        {
            var route = await routeRepository.GetRouteAsync(RouteId.Value);
            if (route == null || route.Creator != userAccount.Id)
            {
                logger.LogWarning("Cannot find route {} or doesn't belong to user {}, ignoring passed route id", RouteId, userAccount.Id);
                RouteId = null;
            }
            else
            {
                RouteName = route.Name;
            }
        }

        var activities = await runLogRepository
            .GetAllLogRunsAsync(userAccount)
            .Where(r => RouteId == null || RouteId == r.RouteId)
            .OrderByDescending(r => r.Date)
            .ThenBy(r => r.CreatedDate)
            .ToListAsync();
        var runLogs = Pagination.Paginate(activities, PageNumber);
        Activities = runLogs.Items;
        Pagination = new(runLogs.Page, runLogs.PageCount);
        Date = (Activities.FirstOrDefault()?.Date ?? DateTime.Today).ToString("yyyy-MM-dd");
    }

    private async Task<UserAccount> GetUserAccountAsync() => _userAccount ??= await userAccountRepository.GetUserAccountAsync(User);

    public async Task<string> RunLogTitleAsync(Models.RunLog runLog) => $"{userService.ToUserDistance(runLog.Route.Distance, await GetUserAccountAsync())} in {paceService.TimeTakenDisplayFormat(runLog.TimeTaken)}";
    public async Task<string> RunLogPaceAsync(Models.RunLog runLog) => paceService.CalculatePace(await GetUserAccountAsync(), runLog);
}

RunnersPal.Core/Pages/Shared/ViewComponents/UserNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RunnersPal.Core.Pages.ViewModels;

namespace RunnersPal.Core.Pages.Shared.ViewComponents;

public class UserNavViewComponent : ViewComponent
{
    public Task<IViewComponentResult> InvokeAsync()
        => Task.FromResult(View(new UserNavModel(Request)) as IViewComponentResult);
}

RunnersPal.Core/Pages/Signin.cshtml.cs
using System.Text;
using Fido2NetLib;
using Fido2NetLib.Objects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunnersPal.Core.Models;
using RunnersPal.Core.Repository;

namespace RunnersPal.Core.Pages;

public class SigninModel(ILogger<SigninModel> logger, IFido2 fido2,
    IUserAccountRepository userAccountRepository)
    : PageModel
{
    [BindProperty(SupportsGet = true)] public string? ReturnUrl { get; set; }
    [BindProperty] public string? Email { get; set; }

    public void OnGet() { }

    public async Task<IActionResult> OnPost()
    {
        logger.LogInformation("Checking user: {Email} / {ReturnUrl}", Email, ReturnUrl);

        if (string.IsNullOrEmpty(Email))
            return Page();

        UserAccount? user;
        string options;
        if ((user = await userAccountRepository.GetUserAccountByEmailAsync(Email)) != null)
        {
            logger.LogTrace("Found existing user account with email [{Email}], creating assertion options", Email);
            options = fido2.GetAssertionOptions(new()
            {
                AllowedCredentials = await userAccountRepository
                    .GetUserAccountAuthenticationsAsync(user)
                    .Select(uac => new PublicKeyCredentialDescriptor(uac.CredentialId ?? []))
                    .ToArrayAsync(),
                UserVerification = UserVerificationRequirement.Discouraged
            }).ToJson();
        }
        else
        {
            logger.LogTrace("Found no user account with email [{Email}], creating request new creds options", Email);
            options = fido2.RequestNewCredential(new()
            {
                User = new Fido2User() { Id = Encoding.UTF8.GetBytes(Email), Name = Email, DisplayName = Email },
                PubKeyCredParams = [],
                AuthenticatorSelection = AuthenticatorSelection.Default,
                AttestationPreference = AttestationConveyancePreference.None
            }).ToJson();
        }

        logger.LogTrace("Created sign in options for: {Email}: {Options}", Email, options);
        return RedirectToPage("./signinverify", routeValues: new { ReturnUrl, Email, VerifyOptions = options });
    }
}

RunnersPal.Core/Pages/Signout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RunnersPal.Core.Pages;

public class SignoutModel : PageModel
{
    public Task<IActionResult> OnGet() => Signout();

    public Task<IActionResult> OnPost() => Signout();

    private async Task<IActionResult> Signout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return Redirect("/");
    }
}

RunnersPal.Core/Pages/Index.cshtml
@page
@model IndexModel

<aside>
    <vc:user-nav />
</aside>

<article>
    <h1>Runners:Pal</h1>
    <div class="rp-home-options">
        <div>
            <h2><a href="/runlog">Log</a></h2>
            <div><a href="/runlog" title="Open your running log"><img src="/images/rundiary.jpg" alt="Run log diary" width="272" height="180" class="rp-calc" /></a></div>
            <div>Keep track of those runs</a></div>
        </div>
        <div>
            <h2><a href="/routepal">Routes</a></h2>
            <div><a href="/routepal" title="Plot and manage all your running routes"><img src="/images/mapping.jpg" alt="Route mapping" width="282" height="180" class="rp-calc" /></a></div>
            <div>Plot your routes on a map and view all your saved routes</div>
        </div>
        <div>
            <h2><a href="/user">Stats</a></h2>
            <div><a href="/user" title="Check out your stats"><img src="/images/chart.jpg" alt="Running stats" width="281" height="180" class="rp-calc" /></a></div>
            <div>Track those all important stats</div>
        </div>
        <div>
            <h2><a href="/calculators">Calculators</a></h2>
            <div><a href="/calculators" title="Calculate running pace, distance, and calories"><img src="/images/stopwatch.jpg" alt="Calculators" width="240" height="180" class="rp-calc" /></a></div>
            <div>Make light work of all the running maths</div>
        </div>
    </div>
</article>

RunnersPal.Core/Pages/RoutePal.cshtml
@page
@model RoutePalModel

<aside>
    <vc:user-nav />
</aside>

<article>
    <p>
    Route mapping
    </p>
    <div id="map"></div>
</article>

@section Head {
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.css">
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.js"></script>
}
@section Scripts {
<script type="text/javascript">
    L.LabelOverlay = L.Layer.extend({
        initialize: function(/*LatLng*/ latLng, /*String*/ label, options) {
            this._latlng = latLng;
            this._label = label;
            L.Util.setOptions(this, options);
        },
        options: {
            offset: new L.Point(0, 2)
        },
        onAdd: function(map) {
            this._map = map;
            if (!this._container) {
                this._initLayout();
            }
            map.getPanes().popupPane.appendChild(this._container);
            this._container.innerHTML = this._label;
            map.on('movestart', this._update_start, this);
            map.on('moveend', this._update_end, this);
            this._update_end();
        },
        onRemove: function(map) {
            map.getPanes().popupPane.removeChild(this._container);
            map.off('movestart', this._update_start, this);
            map.off('moveend', this._update_end, this);
        },
        _update_start: function(){
            L.DomUtil.setPosition(this._container, 0);
        },
        _update_end: function() {
            var pos = this._map.latLngToLayerPoint(this._latlng);
            var op = new L.Point(pos.x + this.options.offset.x, pos.y - this.options.offset.y);
            L.DomUtil.setPosition(this._container, op);
        },
        _initLayout: function() {
            this._container = L.DomUtil.create('div', 'leaflet-label-overlay');
        }
    });

	const map = L.map('map').setView([51.505, -0.09], 10);
	L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
		maxZoom: 19,
		attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
	}).addTo(map);
	L.marker([51.6, 0.09], {
        alt: 'Start of route',
        title: 'Start of route',
        icon: L.icon({ iconUrl: '/images/pin-start.png', iconAnchor: [11, 36] })
    }).addTo(map);

    var endOfRouteMarker = null;
    var lastPoint = [51.6, 0.09];
	function onMapClick(e) {
        L.polyline([lastPoint, e.latlng], {color: '#d866eb'}).addTo(map);
        lastPoint = e.latlng;

        // an example of how we might do the mile / km markers
        map.addLayer(new L.LabelOverlay(lastPoint, '<span class="rp-distance-marker">1</span>'));

        if (endOfRouteMarker === null) {
            endOfRouteMarker = L.marker(lastPoint, {
                alt: 'End of route',
                title: 'End of route',
                icon: L.icon({ iconUrl: '/images/pin-end.png', iconAnchor: [11, 36] })
            }).addTo(map);
        } else {
            endOfRouteMarker.setLatLng(lastPoint);
        }
	}
	map.on('click', onMapClick);
</script>
}

RunnersPal.Core/Pages/RunLog.cshtml
@page
@model RunLogModel

<aside>
    <vc:user-nav />
</aside>

<article>
    <p>
    Run Log
    </p>
    <div class="cal-date-controls">
    <button id="cal-prev-year" title="Previous year">&nbsp;&laquo;&nbsp;</button>
    <button id="cal-prev-month" title="Previous month">&nbsp;&nbsp;&lsaquo;&nbsp;&nbsp;</button>
    <button id="cal-today" title="Go to the current month">Today</button>
    <button id="cal-next-month" title="Next month">&nbsp;&nbsp;&rsaquo;&nbsp;&nbsp;</button>
    <button id="cal-next-year" title="Next year">&nbsp;&raquo;&nbsp;</button>
    </div>
    <div id="cal-date"></div>
    <div id="calendar"></div>
</article>

@section Scripts {
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js" integrity="sha256-ZztCtsADLKbUFK/X6nOYnJr0eelmV2X3dhLDB/JK6fM=" crossorigin="anonymous"></script>
<script type="text/javascript">
$(function() {
    var calendar = new FullCalendar.Calendar(document.getElementById('calendar'), {
        initialView: 'dayGridMonth',
        headerToolbar: false,
        dateClick: function(info) {
            alert('Clicked on: ' + info.dateStr);
        },
        eventClick: function(info) {
            alert('Clicked on: ' + info.event.id);
        },
        eventContent: function(event) {
            return { html: '<span class="rp-event-title">' + event.event.title + '</span>' };
        }
    });
    calendar.render();
    function onDateChange() {
        $('#cal-date').text(calendar.getDate().toLocaleDateString(undefined, { year: 'numeric', month: 'long' }));
    }

    onDateChange();    
    $('#cal-today').click(function() { calendar.today(); onDateChange(); });
    $('#cal-prev-year').click(function() { calendar.prevYear(); onDateChange(); });
    $('#cal-prev-month').click(function() { calendar.prev(); onDateChange(); });
    $('#cal-next-year').click(function() { calendar.nextYear(); onDateChange(); });
    $('#cal-next-month').click(function() { calendar.next(); onDateChange(); });

    calendar.addEvent({ id: 1, title: '3.11 miles in 00:28:37<br/>9:12 min/mile', start: '2024-12-18', allDay: true });
});
</script>
}

RunnersPal.Core/Pages/Signin.cshtml
@page
@model SigninModel

<aside>
    <vc:user-nav />
</aside>

<article>
<h1>Login</h1>

<form action="/signin" method="post">
    <p>
        <label for="email">Email address:</label>
        <input type="email" id="email" name="email" autofocus />
        <button type="submit">Next...</button>
    </p>
    <input type="hidden" name="returnurl" value="@Model.ReturnUrl" />
    @Html.AntiForgeryToken()
</form>
</article>

RunnersPal.Core/Pages/Signout.cshtml
@page
@model SignoutModel

<aside>
    <vc:user-nav />
</aside>

<article>
<h1>Logout</h1>

You have successfully logged out.
</article>